#!/usr/bin/env node
/*
 * Pull lifetime view counts out of a WordPress mysqldump and emit SQL that
 * applies them to beta's Article.viewCount.
 *
 *   node scripts/wp-import/views.js "D:\ayya\20260809 xeetimes_WPTNA.sql" > views.sql
 *
 * The counts come from the Post Views Counter plugin's HLd_post_views table:
 *
 *   id      bigint    WP post ID
 *   type    tinyint   0 = post views (the plugin also stores other counters)
 *   period  varchar   'total' is the lifetime figure; the rest are daily,
 *                     weekly, monthly and yearly buckets ('20210110', '2021',
 *                     '202101', ...) which together make up ~99% of the rows
 *   count   bigint
 *
 * Only period='total' is wanted. Filtering on it is what keeps this from
 * summing a post's views several times over.
 *
 * The join back to beta is Article.id = 'art_' + <WP post ID> — beta's slugs
 * are percent-encoded Dhivehi and carry no post ID at all, so the id column is
 * the only link between the two databases.
 *
 * Counts are applied with GREATEST(), never assigned outright: beta has been
 * live alongside the old site and has accumulated real views of its own. Taking
 * the larger of the two means re-running this can only ever correct a count
 * upward, and running it twice does nothing the first run did not already do.
 */
'use strict';

const fs = require('node:fs');
const readline = require('node:readline');

const dump = process.argv[2];
if (!dump) {
  console.error('usage: node scripts/wp-import/views.js <dump.sql> [--table HLd_post_views]');
  process.exit(1);
}
const tableArg = process.argv.indexOf('--table');
const TABLE = tableArg > -1 ? process.argv[tableArg + 1] : 'HLd_post_views';

const INSERT_RE = new RegExp('^INSERT INTO `' + TABLE + '`');
// (id, type, 'period', count) — period is alphanumeric in this table, so there
// are no escaped quotes to defend against here.
const ROW_RE = /\((\d+),\s*(\d+),\s*'([^']*)',\s*(\d+)\)/g;

const totals = new Map(); // wp post id -> lifetime views
const typesSeen = new Map();
let rows = 0;

const rl = readline.createInterface({
  input: fs.createReadStream(dump, { encoding: 'utf8' }),
  crlfDelay: Infinity,
});

let inTable = false;

rl.on('line', (line) => {
  if (!inTable) {
    if (!INSERT_RE.test(line)) return;
    inTable = true;
  }

  ROW_RE.lastIndex = 0;
  let m;
  while ((m = ROW_RE.exec(line))) {
    rows++;
    const [, id, type, period, count] = m;
    if (period !== 'total') continue;
    typesSeen.set(type, (typesSeen.get(type) || 0) + 1);
    // Should be one 'total' row per post, but take the largest if the dump
    // somehow carries more than one rather than letting order decide.
    const n = Number(count);
    const prev = totals.get(id);
    if (prev === undefined || n > prev) totals.set(id, n);
  }

  // A multi-row INSERT ends at the statement terminator.
  if (/;\s*$/.test(line)) inTable = false;
});

rl.on('close', () => {
  const err = (s) => process.stderr.write(s + '\n');
  err(`scanned ${rows.toLocaleString()} view rows in ${TABLE}`);
  err(`type values on 'total' rows: ${[...typesSeen].map(([t, c]) => `${t}=${c}`).join(', ')}`);
  err(`posts with a lifetime total: ${totals.size.toLocaleString()}`);

  const counts = [...totals.values()].sort((a, b) => b - a);
  err(`highest: ${counts[0]?.toLocaleString()}   median: ${counts[Math.floor(counts.length / 2)]?.toLocaleString()}   zero: ${counts.filter((c) => c === 0).length}`);

  const out = process.stdout;
  out.write('-- Generated by scripts/wp-import/views.js — do not edit by hand.\n');
  out.write('BEGIN;\n');
  out.write('CREATE TEMP TABLE wp_views (wp_id text PRIMARY KEY, views integer) ON COMMIT DROP;\n');

  // One multi-row INSERT per chunk: a single statement with 3k VALUES rows is
  // fine, but chunking keeps the file readable and the parser's memory flat.
  const entries = [...totals].filter(([, v]) => v > 0);
  const CHUNK = 500;
  for (let i = 0; i < entries.length; i += CHUNK) {
    const slice = entries.slice(i, i + CHUNK);
    out.write('INSERT INTO wp_views (wp_id, views) VALUES\n');
    out.write(slice.map(([id, v]) => `  ('art_${id}', ${v})`).join(',\n'));
    out.write('\nON CONFLICT (wp_id) DO UPDATE SET views = EXCLUDED.views;\n');
  }

  out.write(`
-- What is about to change, before it changes.
SELECT count(*) AS matched_articles,
       count(*) FILTER (WHERE w.views > a."viewCount") AS will_increase,
       sum(w.views - a."viewCount") FILTER (WHERE w.views > a."viewCount") AS views_added
FROM wp_views w JOIN "Article" a ON a.id = w.wp_id;

UPDATE "Article" a
   SET "viewCount" = GREATEST(a."viewCount", w.views)
  FROM wp_views w
 WHERE a.id = w.wp_id
   AND w.views > a."viewCount";

COMMIT;
`);

  err(`emitted ${entries.length.toLocaleString()} non-zero counts`);
});
