#!/usr/bin/env node
/*
 * Read CURRENT view counts straight off the old WordPress site and emit the SQL
 * to apply them.
 *
 *   node scripts/wp-import/views-live.js ids.txt > views-live.sql
 *
 * Companion to views.js, which reads a mysqldump. A dump is a snapshot: any
 * article published after it was taken has no counts at all, and recent
 * articles — the ones still accruing views fastest — are the most stale. This
 * reads the live figure instead, so it fills both gaps.
 *
 * The Post Views Counter plugin exposes:
 *
 *   /wp-json/post-views-counter/get-post-views/<ids>   read
 *   /wp-json/post-views-counter/view-post/<id>         INCREMENTS — never call
 *
 * The read route accepts a comma-separated list but returns the SUM, not a
 * breakdown, so it has to be one request per article.
 *
 * ONE-SHOT TOOL. It only works while the old site is still reachable, and the
 * counts it reads stop moving once the domain no longer points there. Take a
 * final pass before the old host is decommissioned; after that, views.js
 * against the last dump is the only source left.
 *
 * Requests are pinned to the old host's IP because xeetimes.com now resolves to
 * the NEW site — asking the domain normally would return the new site's counts,
 * which are exactly what we are trying to fill in.
 */
'use strict';

const fs = require('node:fs');
const { execFile } = require('node:child_process');

const idsFile = process.argv[2];
if (!idsFile) {
  console.error('usage: node scripts/wp-import/views-live.js <ids.txt> [--host <ip>]');
  process.exit(1);
}
const hostArg = process.argv.indexOf('--host');
const OLD_HOST_IP = hostArg > -1 ? process.argv[hostArg + 1] : '162.241.224.128';
const DOMAIN = 'www.xeetimes.com';

const ids = fs
  .readFileSync(idsFile, 'utf8')
  .split(/\r?\n/)
  .map((s) => s.trim())
  .filter((s) => /^\d+$/.test(s));

const err = (s) => process.stderr.write(s + '\n');
err(`reading live counts for ${ids.length} articles from ${OLD_HOST_IP}`);

// curl, not fetch. Host is a forbidden header name in undici, so fetch drops it
// silently and every request lands on the bare IP — which shared cPanel hosting
// answers with someone else's holding page, not our site. curl --resolve pins
// the DNS answer instead of overriding the header, which is what is actually
// wanted: real SNI and a real Host, just pointed at a chosen address.
function viewsFor(id) {
  const url = `https://${DOMAIN}/wp-json/post-views-counter/get-post-views/${id}`;
  return new Promise((resolve) => {
    let attempt = 0;
    const run = () => {
      execFile(
        'curl',
        ['-s', '--max-time', '15', '--resolve', `${DOMAIN}:443:${OLD_HOST_IP}`, url],
        (error, stdout) => {
          const text = (stdout || '').trim();
          if (!error && /^\d+$/.test(text)) return resolve(Number(text));
          if (++attempt < 3) return run();
          resolve(null);
        },
      );
    };
    run();
  });
}

(async () => {
  const results = [];
  let failed = 0;

  // Modest concurrency: the old host is shared cPanel hosting and a burst of
  // parallel requests gets throttled, which reads as failure rather than delay.
  const CONCURRENCY = 6;
  let cursor = 0;
  await Promise.all(
    Array.from({ length: CONCURRENCY }, async () => {
      while (cursor < ids.length) {
        const id = ids[cursor++];
        const v = await viewsFor(id);
        if (v === null) {
          failed++;
          err(`  ${id}: no answer after 3 tries`);
        } else if (v > 0) {
          results.push([id, v]);
        }
        if (results.length % 25 === 0 && results.length) err(`  ${results.length}/${ids.length}…`);
      }
    }),
  );

  err(`got counts for ${results.length}, failed ${failed}`);
  if (!results.length) {
    err('nothing to write — is the old host still reachable at that IP?');
    process.exit(1);
  }

  const out = process.stdout;
  out.write('-- Generated by scripts/wp-import/views-live.js — do not edit by hand.\n');
  out.write('BEGIN;\n');
  out.write('CREATE TEMP TABLE live_views (wp_id text PRIMARY KEY, views integer) ON COMMIT DROP;\n');
  out.write('INSERT INTO live_views (wp_id, views) VALUES\n');
  out.write(results.map(([id, v]) => `  ('art_${id}', ${v})`).join(',\n'));
  out.write('\nON CONFLICT (wp_id) DO UPDATE SET views = EXCLUDED.views;\n');
  out.write(`
SELECT count(*) AS matched,
       count(*) FILTER (WHERE l.views > a."viewCount") AS will_increase,
       sum(l.views - a."viewCount") FILTER (WHERE l.views > a."viewCount") AS views_added
FROM live_views l JOIN "Article" a ON a.id = l.wp_id;

-- GREATEST, as in views.js: beta has its own genuine views and must never lose
-- them to an older figure from the other site.
UPDATE "Article" a
   SET "viewCount" = GREATEST(a."viewCount", l.views)
  FROM live_views l
 WHERE a.id = l.wp_id
   AND l.views > a."viewCount";

COMMIT;
`);
})();
